const fs = require('fs-extra');

fs.ensureDirSync('folder1');
console.log('Создали папку folder1');
fs.writeFileSync('folder1/text.txt', 'Привет, это текстовый файл');
console.log('Создали файл text.txt в folder1');
fs.ensureDirSync('folder2');
console.log('Создали папку folder2');
fs.moveSync('folder1/text.txt', 'folder2/text.txt');
console.log('Переместили файл из folder1 в folder2');
fs.ensureDirSync('folder3');
console.log('Создали папку folder3');
fs.copySync('folder2/text.txt', 'folder3/text.txt');
console.log('Скопировали файл из folder2 в folder3');
fs.writeJsonSync('folder1/data.json', { name: 'myName' });
console.log('Создали файл data.json в folder1');
const data = fs.readJsonSync('folder1/data.json');
console.log('Содержимое JSON:', data);
fs.removeSync('folder2/text.txt');
fs.removeSync('folder3/text.txt');
fs.removeSync('folder1/data.json');
console.log('Удалили файлы');
fs.removeSync('folder1');
fs.removeSync('folder2');
fs.removeSync('folder3');
console.log('Удалили папки');